FROM grafana/grafana:latest

USER root

RUN apk update && apk add curl

# Change the default data directory (otherwise grafanadb won't persist)
RUN mkdir /var/lib/grafanadb
ENV GF_PATHS_DATA /var/lib/grafanadb

COPY ./init.sh .

# Init Grafana and preconfigure data source to be influxdb
RUN ./init.sh

CMD ["/run.sh"]
